### ISSUE TITLE
Empty a dbf file

### ISSUE THREAD

**Issue by sfblap** [albfernandez/javadbf#10]
i have a dbf file and I want to delete all record of this file (still keep fileds)
I can do that?
thank you very much

**Comment by albfernandez** [comment]
You cannot do that with javadbf, instead yo could create an empty dbf file using the other as template, as in this example: 
https://github.com/albfernandez/javadbf/blob/master/src/test/java/com/linuxense/javadbf/CreateEmptyFileFromTemplateTest.java

**Comment by sfblap** [comment]
thank you!
