### ISSUE TITLE
DBFReader#skipRecords：Is it possible to optimize the performance of this method

### ISSUE THREAD

**Issue by DestinyL** [albfernandez/javadbf#100]
- now is for loop.If no deleted, is there a better way to implement.Tried it directly "skip"，no problem（please confirm，thanks）.

- then，Is there a better solution to keep the status quo?

**Comment by albfernandez** [comment]
Hi
If there are deleted rows the only way is to read all of them (because you need to read it to check the deleted field to discard the  deleted row).
Can be optimized if all deleted records has been read (track the total records, the file size and the deleted records already discarded, but I think it's too complicate for the small benefit)

**Comment by DestinyL** [comment]
thanks a lot.And then,If there is no delete behavior, is it possible to directly call "skip(int bytesToSkip)".So far by testing, everything seems to be fine, is it possible to do so.

**Comment by DestinyL** [comment]
> Hi If there are deleted rows the only way is to read all of them (because you need to read it to check the deleted field to discard the deleted row). Can be optimized if all deleted records has been read (track the total records, the file size and the deleted records already discarded, but I think it's too complicate for the small benefit)

thanks a lot.And then,If there is no delete behavior, is it possible to directly call "skip(int bytesToSkip)".So far by testing, everything seems to be fine, is it possible to do so.

**Comment by gxywy** [comment]
> > Hi If there are deleted rows the only way is to read all of them (because you need to read it to check the deleted field to discard the deleted row). Can be optimized if all deleted records has been read (track the total records, the file size and the deleted records already discarded, but I think it's too complicate for the small benefit)
> 
> thanks a lot.And then,If there is no delete behavior, is it possible to directly call "skip(int bytesToSkip)".So far by testing, everything seems to be fine, is it possible to do so.

same issue, call `nextRecord()` is slow, i also think call `skip(int bytesToSkip)` is more efficient
