### ISSUE TITLE
languageDriver is 0

### ISSUE THREAD

**Issue by zhangdan-dev** [albfernandez/javadbf#107]
dbf文件解析字符编码为null,发现languageDriver值为0 。一般是什么原因呢？
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/73986520/196697364-7842abc2-24e6-4128-850a-1fd23b8f5cbc.png">

**Comment by albfernandez** [comment]
I'm not sure you are using this javadbf, it seems you are using another clone.

But I try to help you.
I assume you've created the dbf file with the java library.
There is a list of "officially supported" charsets on dbf files. When you create a dbf file with javadbf, the file is created , and if the charset supplied is "not supported", isntead of fail, it creates the file but register with "languageDriver=0"

When you read this files with javadbf, you must indicate to DBFReader the charset to use.
