### ISSUE TITLE
Adding posibility to read string without spaces

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [albfernandez/javadbf#11]
As I understand `dbf` format itseft needs a padding, because string have to be with exact size. But when string is deserialized into object extra spaces are not needed. So it is often leads to remove spaces from rest of string. From other side removing spaces can be an issue when it is not needed. So I suggest to add some property like `trimRightSpaces`, which is set to false by default, but when it is set to true, the reader automatically remove right extra spaces.

**Comment by albfernandez** [comment]
Done, will be released on 1.0.0 and trimming will be enabled by default
