### ISSUE TITLE
Apache license for an Apache Camel component

### ISSUE THREAD

**Issue by jeremyross** [albfernandez/javadbf#113]
Hi,

I was wondering if there's interest in offering an Apache 2.0 License for the specific purpose of being used in an Apache Camel DBF component. I'm currently developing the component, and would love to be able to include it in the official Apache Camel project.

Thanks for your consideration.

**Comment by albfernandez** [comment]
Hi
I'm not the original author of JavaDBF. This is a fork. I know I can continue working with the same licensing (LGPL) but i'm not sure i can relicense it.

**Comment by jeremyross** [comment]
I see. Looks like you forked the original repo a long time ago. Is the original repo on github?

**Comment by albfernandez** [comment]
Hi

Sorry for the big delay.

The project was first hosted in http://sarovar.org/projects/javadbf/ ,  but it was shutdown a long time ago
It was migrated to https://code.google.com/archive/p/javadbf/.
There is a fork on https://github.com/tbzfish. That fork is a mirror of Google code repository, I think this mirror is not created by the original author, but I'm not sure.
