### ISSUE TITLE
Write data to OutputStream in Sync Mode

### ISSUE THREAD

**Issue by sfblap** [albfernandez/javadbf#24]
Does Sync Mode faster normal mode?
If so, You can support OutputStream or InputStream as param in constructer of DBFWriter instead of File?
(I on web eviroment, allow get data from database and write to object to client download. i can only create new OutputStream or InputStream to use,  which can not be used directly File because can conflig when many client use that file)

**Comment by albfernandez** [comment]
You can use two approach to create DBF files with javaDBF

1. Creating a DBFWriter with empty constructor and calling at the end to write(outputStream). This method store full dbf file in memory until write is called.
1. Creating DBFWriter with file constructor, records are added to the file directly, and when you call close it update header to reflect changes.

So method 1 uses a lot of memory if your dbf is big (depending concurrent users, big could be 1Mb or 10Mb).
If your dbf files are small you can use safely method 1, if the files are big, you have to use method 2. If you are on servlet enviroment, you must be carefull on file names. You can create a temp File with File.createTempFile or you can use UUID to generate an unique name.

Maybe for next release i'll add a new constructor for OutputStream and deprecate write method, I think it's clearer than current API.

**Comment by sfblap** [comment]
thank you very much!
