### ISSUE TITLE
Publish javadbf in mvn public repositories

### ISSUE THREAD

**Issue by albfernandez** [albfernandez/javadbf#3]
Publish javadbf to sonatype.org to be added to the main online maven repositories.

Suggested by @ffradegrada

**Comment by albfernandez** [comment]
Done

**Comment by ffradegrada** [comment]
Cool! Is that an automatic update or maybe they have to validate it?

**Comment by albfernandez** [comment]
It's uploaded and ok now.
It's under other groupId because I'm not the original author (I suppose I can't use the older one). To use in your project you have to put this lines in your pom.xml

    <dependency>
        <groupId>com.github.albfernandez</groupId>
        <artifactId>javadbf</artifactId>
        <version>0.6.2</version>
    </dependency>
