### ISSUE TITLE
setCharset method not sets charset in dbf file

### ISSUE THREAD

**Issue by kitemeall** [albfernandez/javadbf#34]
```
//DBFBase

public void setCharset(Charset charset) {
		this.charset = charset;
	}
```

this method hasn't been overloaded in `DBFWriter` file,
and if you call 
`dbfWriter.setCharset(charset)`
it doestn't change the charset in `DBFHeader` inner object,
and when you try to write DBF, the 29th byte in resulting output streem is set in default charset value.
(now it's 3)

It's needed to overload  setCharset method in `DBFWriter` class

**Comment by albfernandez** [comment]
If you want to provide a charset, you must use the appropriate constructor.

Maybe setCharset method should be protected.

**Comment by albfernandez** [comment]
If you think the solution is enough, please close the issue.
If not, please provide more information or some example / test
