### ISSUE TITLE
IBM866 and IBM865 charset are mixed up in DBFCharsetHelper

### ISSUE THREAD

**Issue by kitemeall** [albfernandez/javadbf#35]
IBM866 charset have to set 29th byte in value 0x65
and IBM865 charset have to set 29th byte in value 0x66
![image](https://user-images.githubusercontent.com/14822181/30415788-4b74c66a-9932-11e7-9abf-e584e885c059.png)
(I hadn't found an english proof)
http://www.autopark.ru/ASBProgrammerGuide/DBFSTRUC.HTM

But they are mixed up in DBFCharsetHelper
```
if ("IBM865".equalsIgnoreCase(charsetName)) {
			return 0x65;
}
if ("IBM866".equalsIgnoreCase(charsetName)) {
		return 0x66;
}
```

**Comment by albfernandez** [comment]
Another source:
https://msdn.microsoft.com/en-us/library/8t45x02s(v=vs.80).aspx

I checked a bad source for this ....
