### ISSUE TITLE
Error reading a DBF file

### ISSUE THREAD

**Issue by thecko** [albfernandez/javadbf#37]
I'm parsing a file and I get this error when I call reader.nextRecord():

> com.linuxense.javadbf.DBFException: Failed to parse Float: Character T is neither a decimal digit number, decimal point, nor "e" notation exponential mark.

It's something about a field definition not matching the value in the DBF maybe? Is there any way to avoid this? I don't even need all the fields in the DBF, but I can't change the structure (I'm reading the DB of an 3rd party program).

Many thanks,

**Comment by albfernandez** [comment]
Can you provide a sample file? (no confidential data, please)

**Comment by thecko** [comment]
I'll try to empty one file ASAP and upload it, now it's fulfilled with sensitive data. If you want, you can check https://github.com/iryndin/jdbf I tried with it's DBF reader and it not fails.

Muchas gracias ;)

**Comment by thecko** [comment]
Next you can find the DBF file. I think it's about the "Logical" field that contains sometimes the "F" value. maybe?

[dbf.zip](https://github.com/albfernandez/javadbf/files/1388342/dbf.zip)

**Comment by albfernandez** [comment]
I need a file with at least one failing row. It seems that there is logical value in a Numerical field, or at least javadbf is trying to read this field as a number.

**Comment by medari1048** [comment]
DBF files : https://github.com/chinna1048/dbf_files

> I need a file with at least one failing row. It seems that there is logical value in a Numerical field, or at least javadbf is trying to read this field as a number.

Hi, check this dbf files, this are related to above issues , 
https://github.com/chinna1048/dbf_files
