### ISSUE TITLE
support DBC files

### ISSUE THREAD

**Issue by ialek36** [albfernandez/javadbf#42]
Quick question.  Do you support DBC files?  It should be just a DBF file with the same header, but the data is compressed using DEFLATE?

**Comment by albfernandez** [comment]
Not at the moment. If the format is as you say, then it should be easy to implement.
Do you have any sample file (or link)?
Is DBC an "official" FoxPro filetype or is a custom format?
Thanks

**Comment by ialek36** [comment]
I'm not sure how official it is.  I know this format is used by Brazilian Government.

Here's the link to a C implementation of the same.  There're a couple of sample files attached there.  I used your project to read the file from the project and some of the Brazilian files.  The code would read the header correctly, but wouldn't be able to parse the actual data.  The later is expected as your code is not decompressing the data.

https://github.com/eaglebh/blast-dbf
