### ISSUE TITLE
Throw runtime 'FieldNotFoundException extends DBFException' when a given field not found

### ISSUE THREAD

**Issue by ciukstar** [albfernandez/javadbf#45]
Throw runtime **FieldNotFoundException extends DBFException** when a given field <FIELD_NAME> not found

**Comment by albfernandez** [comment]
Please check the commit is valid for you

**Comment by ciukstar** [comment]
Thank you! May I ask you if there are some backward compatibility constraints imposed. I'd prefer something more 'functional', 'stream like' processing of a DBF.

**Comment by albfernandez** [comment]
I wish to support java 7 for the moment (and I've not much time for adding new features)

If you like to contribute a PR, maybe I could release javaDBF 2.0 with supports only jdk 8 and above.
