### ISSUE TITLE
Discrepancy between code and readme regarding writeable data types

### ISSUE THREAD

**Issue by vincent-dm** [albfernandez/javadbf#52]
According to [the readme](https://github.com/albfernandez/javadbf/blob/master/README.md), the following data types are writable:
> * Character (C)
> * Numeric (N)
> * **Double (F)**
> * Logical (L)
> * Date (D)

However, if I look at the ENUM definitions in `com.linuxense.javadbf.DBFDataType`, the following data types have `writeSupported` set to `true`:
* `CHARACTER` (C)
* `DATE` (D)
* **`FLOATING_POINT` (F)**
* `LOGICAL` (L)
* `NUMERIC` (N)

 They contradict each other regarding the writability of Double/Float. I assume you meant to indicate `Float` as writable in the readme?

PS: thanks for making this library, it's a huge time saver for me!

**Comment by albfernandez** [comment]
FLOATING_POINT is the name dBase uses for some sort of storing floating point data (it's as NUMERIC but a little bigger)

https://www.clicketyclick.dk/databases/xbase/format/data_types.html

It's confusing, so i've updated the Readme.

**Comment by albfernandez** [comment]
I'm not the only author of the library, credits must be given also to

Jan Schlößin
Anil Kumar K

The made the original version, which I've forked.
