### ISSUE TITLE
support columns number > 255

### ISSUE THREAD

**Issue by gba3455** [albfernandez/javadbf#53]
I want to create a DBF file which columns number > 255 by javadbf.
for example: |P1|P2|P3|.......|P346|  <-columns
I created DBF by javadbf and it's only has 255 columns...

please tell me how to solve this issue.
Thx

**Comment by albfernandez** [comment]
There is a limit of 255 columns in dbf engines

https://docs.microsoft.com/en-us/previous-versions/visualstudio/foxpro/3kfd3hw9(v=vs.80)

I've tested javadbf to create and open a file with more of 255 files and appear to work fine.

I'm not sure if it's safe to throw an exception if yo try to create a dbf file with more than 255 files, or write a line in the docs to warn about it.
