### ISSUE TITLE
IndexOutOfBoundsException when calling DBFReader#nextRecord()

### ISSUE THREAD

**Issue by Hsiungchun** [albfernandez/javadbf#56]
The four lines from the stack trace are as follows

> java.lang.IndexOutOfBoundsException: Index: 13, Size: 13
>  at java.util.ArrayList.rangeCheck(ArrayList.java:657)
>  at java.util.ArrayList.get(ArrayList.java:433)
>  at com.linuxense.javadbf.DBFReader.nextRecord(DBFReader.java:327)
> ……

I found somewhere strange that may cause the problem. Whether should use `recordObjects.get(j)` instead of `recordObjects.get(i)` in `DBFReader.java: 327`?

Thanks!

**Comment by albfernandez** [comment]
VARCHAR and VARBINARY are not tested. Could you provide a sample  file (no private data!!!) to test this type of fields and fix de bug? thanks

**Comment by Hsiungchun** [comment]
A sample file is shown below. In addition, it seems to apply to issues #25 and #26 . 

[javadbf#issue#56-testdata.zip](https://github.com/albfernandez/javadbf/files/3255021/javadbf.issue.56-testdata.zip)

Thank you for your attention.

**Comment by albfernandez** [comment]
I've relases a new version (1.9.4). I hope it fixed your issue, could you try and confirm please?

**Comment by Hsiungchun** [comment]
The latest release works. Thanks for your help!
