### ISSUE TITLE
Read character field with length >33

### ISSUE THREAD

**Issue by olnow** [albfernandez/javadbf#60]
Hello!

 I have a problem with read some dbf file.
 File reads, but character field with length 100 reads only 33 character.
 DBF Viewer defines file format: FoxBase+/dBase 3 PLUSE, no memo.
 Field length - 100 character.

 Please tell me how to solve this issue.
 Thanks
[111.zip](https://github.com/albfernandez/javadbf/files/3734230/111.zip)

**Comment by albfernandez** [comment]
I think javadbf is triming your string. 
you can change this behaviour
```java
    reader = new DBFReader(new FileInputStream(testFile));
    reader.setTrimRightSpaces(false);
```

**Comment by olnow** [comment]
Thank you for answer.

The problem was be in trim, but not in javadbf.
It was in my trim function. Moreover trim string from the middle of the word.

Thanks.
