### ISSUE TITLE
java.lang.IllegalArgumentException: No support for writting TIMESTAMP

### ISSUE THREAD

**Issue by szabotakacsb** [albfernandez/javadbf#65]
I use javadbf1.11.0.jar. 
I have created a field with fields[n].setType(DBFDataType.TIMESTAMP); 
where the value (rowData object) is date with SimpleDateFormat("yyyy-MM-dd HH:mm:ss");. 

Why I got java.lang.IllegalArgumentException: Not support for writing TIMESTAMP?

**Comment by albfernandez** [comment]
Timestamp write support is not yet implemented, sorry

#27
