### ISSUE TITLE
How to write a cyrilics strings?

### ISSUE THREAD

**Issue by ignattru** [albfernandez/javadbf#66]
If i create a records in russian lang in DBF file i get questions (??????? ???) instead symbols. Can i fix this problem?

**Comment by albfernandez** [comment]
I'm not sure what is your question, but i'll try to help you.

First, you should create the DBFWriter indicating your russian charset (maybe windows-1251?)

```java
DBFWriter writer = new DBFWriter(out, Charset.forName("windows-1251"));
```

For reading, JavaDBF should autodetect encoding, but you can force it

```java
// Autodected
DBFReader reader = new DBFReader(in);

// forced
DBFReader reader = new DBFReader(in, Charset.forName("windows-1251"));
```

If you found a bug or need more help please provide a sample (although I can't read Russian !!! )
