### ISSUE TITLE
Keeping special chars with windows-1252

### ISSUE THREAD

**Issue by LethalGiraffe** [albfernandez/javadbf#67]
Hi there !

I'm looking to produce files containing various french specific characters such as contained in "**Vandœuvre-lès-Nancy**" (which is a french town name that have a '**œ**' and a '**è**' as specific characters).

As far as I understand I need to set "**windows-1252**" as character encoding in order to avoid getting question marks in the result.
 
If I don't set anything as character encoding I do get this: "**Vand?uvre-lès-Nancy**".

So I create the writer like this:
`DBFWriter dbfWriter = new DBFWriter(new FileOutputStream(dbfFile), Charset.forName("windows-1252"));`

But in the final file instead of getting "**Vandœuvre-lès-Nancy**" I do get "**Vand£uvre-lÞs-Nancy**" where every special character has been replaced by... something else.

I also tried using **ISO-8859-15** but without success. The data is being pulled from an UTF-8 database.

Do you have any clue on what' is going on and how I can solve this problem to get the string as expected in the final file ?

Thank you in advance.

Regards :)

**Comment by albfernandez** [comment]
I can't confirm it works, What program are you using to read the generated dbf file?

I've created a small demo in https://github.com/albfernandez/javadbf/commit/788b61cb765508903e778f281a3bbe8452efb174 and seems to work fine

**Comment by LethalGiraffe** [comment]
I tried the code that you provided in your demo and the result is still te same.
I am using DBF View and/or Mircrosoft Excel 2016.
