### ISSUE TITLE
Feature proposal: augment DBFReader's API to retrieve a column by its name

### ISSUE THREAD

**Issue by adiknoth** [albfernandez/javadbf#69]
Hi!

First time DBF user here, so I might miss something. I'm only interested in reading certain columns that I know by name, not by position.

For that, I iterate over all fields and track their names: (Kotlin code, close enough to Java I hope)

```
            val numberOfFields = reader.fieldCount
            var fieldIndexFromName = mutableMapOf<String, Int>()
            for (i in 0 until numberOfFields) {
                val field = reader.getField(i)

                // The API is positional, one cannot ask for "give me column name foo".
                // Instead, build a map from column name to index number.
                fieldIndexFromName[field.name] = i
            }
```

Maybe the reader class could do that upon opening the file and provide such a mapping. Any API would do, either getFieldNumberByName(string) -> int or ultimately

   rowObjects.getByName(string)

which is really just

   rowObjects.get(reader.getFieldNumberByName(string)

**Comment by albfernandez** [comment]
Hi!
I think it's already done
use reader.nextRow() instead of nextRecord.
DBFRow allows you to retrieve the data by column name
