### ISSUE TITLE
Add BigDecimal type instead of Double

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [albfernandez/javadbf#7]
Using Double can lead to loose some values, because `Doube` can not be mapped to any decimal value. Could you please add possibility to convert `dbf` number format to `BigDecimal`? A property can be added for switching between BigDecimal and Double.

**Comment by albfernandez** [comment]
It's a backward compatible feature. I think it's time to release 1.0 and use only BigDecimal for this. (you can always invoke doubleValue if you need a double.
Data in dbf file is stored as string, decimal format, so BigDecimal is the correct type.
