### ISSUE TITLE
Question about speed of write file

### ISSUE THREAD

**Issue by FloatingMaple** [albfernandez/javadbf#70]
I used `DBFWriter write = new DBFWriter(new File(path))` and write 100,000 rows data, each row has 18 columns. Write the dbf file speed about 16 seconds.

is this a normal speed?  Can it be faster? 

(version is 1.11.1 )

**Comment by albfernandez** [comment]
I've not benchmarks in javadbf. Speed is not a priority (but you can help if you want).

Maybe javadbf can be optimized: currently it dows an I/O Operation for field in "file mode", and can be grouped to one write per row (generating the row in memory)
I'll take a look
