### ISSUE TITLE
java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by shadiyev** [albfernandez/javadbf#72]
Is there a version of javaDBF compatible with Java version 1.6 (class file version 50)?

**Comment by albfernandez** [comment]
I've committed some changes to compile to 1.6.
The classformat will be correct but there are some API calss that need to be changed 

[javadbf-1.12.0-SNAPSHOT.jar.zip](https://github.com/albfernandez/javadbf/files/5264275/javadbf-1.12.0-SNAPSHOT.jar.zip)

**Comment by shadiyev** [comment]
Now it throws java.io.EOFException. I've checked my file on local machine with javadbf-1.11.2 and Java 8 and it works fine.

**Comment by albfernandez** [comment]
Can yo provide a StackTrace of the error or a sample dbf file (no confidential data please) ?
