### ISSUE TITLE
Question about CDX indexe files

### ISSUE THREAD

**Issue by dprutean** [albfernandez/javadbf#81]
I am not experienced with DBF, but I got a task to look at the CDX files.  Do these files contains relevant data? Can the driver read these files?

**Comment by albfernandez** [comment]
The cdx files are indexes to speed reading and searching  into the main dbf  file

https://www.clicketyclick.dk/databases/xbase/format/cdx.html#CDX_STRUCT

**Comment by albfernandez** [comment]
Javadbf only read dbf and dbt files

**Comment by bich30** [comment]
I add another url where it explains the same but in a visually cleaner way:
   https://docs.microsoft.com/en-us/previous-versions/visualstudio/foxpro/s8tb8f47(v=vs.80)
   https://docs.microsoft.com/en-us/previous-versions/visualstudio/foxpro/k35b9hs2(v=vs.71)

I hope it doesn't bother @albfernandez, I have found on github the code to implement the cdx indices.
Currently I am trying, if I succeed I share it with everyone.
   https://github.com/Chessforeva/JavaFoxDBF/blob/master/cdx.java

**Comment by edmarfrazao** [comment]
Working with DBF and CDX indices
I am also interested in the driver supporting the FoxPro Standard TAG CDX indices
XHarbour Development in Delphi
