### ISSUE TITLE
[BUG] When reading from double, the data type is lost

### ISSUE THREAD

**Issue by baizhi1989** [albfernandez/javadbf#82]
When reading from double, the data type is lost

example:

Field numeric type, width 18, scale 2

Original data "99999999999999.99"

DBFReader output data "9.999999999998e13" and the data type is double

Data of type BigDecimal should be output

**Comment by albfernandez** [comment]
Hi

What version of javaDBF are you using? In 1.0 this should return BigDecimal, seems you're using old pre 1.0 version?
Could you provide a sample file without private data?

**Comment by baizhi1989** [comment]
sorry, the page "https://github.com/albfernandez/javadbf " show the lastest version is  JavaDBF 0.11.1, but i click "https://github.com/albfernandez/javadbf/releases", i see the lastest version 1.11.2
thank you !
![image](https://user-images.githubusercontent.com/10275590/112446701-718d7a80-8d8b-11eb-8005-531688aa3c03.png)
