### ISSUE TITLE
Data confusion

### ISSUE THREAD

**Issue by Qumans** [albfernandez/javadbf#84]
reader.nextRecord(); When reading a large batch of database data, the values returned by the fields are all confused. 

com.linuxense.javadbf.DBFReader#nextRecord

eg:  Field{FieldA  FieldB  FieldC  FieldD} value{"AA","BB","CC","DD";  "AA","BB","CC","DD"; "AA","BB","CC","DD";}
read result： Field{FieldA  FieldB  FieldC  FieldD} value{"A","ABB",null,"CCDDA";  "A","BBCC","null","DD"; "A","ABB","CCD","D";}

When I add a thread to sleep between two reader.nextRecord()；
eg：
![image](https://user-images.githubusercontent.com/56535994/114387349-e43c8980-9bc4-11eb-8cf2-54dceeefad00.png)

it  is  worked for we;

But this is more time-consuming, I hope you can solve it

**Comment by albfernandez** [comment]
Hi

some questions to debug this.
- What version of javadbf are you using?
- How do you create javadbfReader?
- Are you using javadbf from more than one thread? (javadbf is not thread safe)
- how big is your file? Does it ocurrs on small files?
- the file is located on a network drive, a local harddisk or ssd?

**Comment by Qumans** [comment]
What version of javadbf are you using?
&nbsp; &nbsp; &nbsp; &nbsp; 1.9.2&nbsp; and 1.11.1 and 1.11.2

How do you create javadbfReader?
&nbsp; &nbsp; &nbsp; &nbsp; FTPClient ftp = util.getFTPClient(ftpHost, Integer.parseInt(ftpPort), ftpUserName,ftpPassword);
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;InputStream in = ftp.retrieveFileStream(new String(file.getName().getBytes("GBK"),"GBK"));
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;DBFReader reader = new DBFReader(in);

Are you using javadbf from more than one thread? (javadbf is not thread safe)
&nbsp; &nbsp; &nbsp; &nbsp; no,I use in single thread

how big is your file? Does it ocurrs on small files?
&nbsp; &nbsp; &nbsp; &nbsp; about 6M，20000 records;&nbsp; &nbsp;Haven't tried small files

the file is located on a network drive, a local harddisk or ssd?
&nbsp; &nbsp; &nbsp; &nbsp; on FTP ；





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "albfernandez/javadbf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 凌晨1:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [albfernandez/javadbf] Data confusion (#84)





 
Hi
 
some questions to debug this.
  
What version of javadbf are you using?
 
How do you create javadbfReader?
 
Are you using javadbf from more than one thread? (javadbf is not thread safe)
 
how big is your file? Does it ocurrs on small files?
 
the file is located on a network drive, a local harddisk or ssd?

**Comment by albfernandez** [comment]
have you tried to wrap your inputStream in a BufferedInputStream? or download to a temporary local file and then read from this?

**Comment by albfernandez** [comment]
I've released 1.13, check if it works for you
