### ISSUE TITLE
encoding utf-8 not working

### ISSUE THREAD

**Issue by sfblap** [albfernandez/javadbf#9]
thank you for this library
i have a problem about encoding  as follows:
`

		DBFField fields[] = new DBFField[1];
		fields[0] = new DBFField();
		fields[0].setName("abc");
		fields[0].setType(DBFDataType.CHARACTER);
		fields[0].setFieldLength(10);

		DBFWriter writer = new DBFWriter(Charset.forName("UTF-8"));
		writer.setFields(fields);
		Object rowData[] = new Object[1];
		
		rowData[0] = "Cộng hòa xã hội";

		writer.addRecord(rowData);
		FileOutputStream fos = new FileOutputStream("E:\\SFB\\Desktop\\hihi.dbf");
		writer.write(fos);
		fos.close()

`
but the results were shown as follows:

![capture](https://cloud.githubusercontent.com/assets/19963491/22726504/4774c3c6-ee06-11e6-8e16-1da4f69bc167.PNG)
you help me soon. thank your very much!

**Comment by albfernandez** [comment]
DBF doesn't support (as i kown) UTF-8. If you have a working file encoded with utf-8 please send me.

According to MS doc these are the supported ANSI encodings:
https://msdn.microsoft.com/en-us/library/aa975345(v=vs.71).aspx

You can check the names used in javadbf here:
https://github.com/albfernandez/javadbf/blob/master/src/main/java/com/linuxense/javadbf/DBFCharsetHelper.java

**Comment by sfblap** [comment]
thank you !
i have a file as following:
[Canhan_ALL_07.zip](https://github.com/albfernandez/javadbf/files/762596/Canhan_ALL_07.zip)

i want to create a file with character encoding same that file
can you help me?

**Comment by albfernandez** [comment]
This file is marked as windows-1252. I don't understand the characters in the file, so i cannot determine if it's ok. You can try to create the file 
DBFWriter writer = new DBFWriter(Charset.forName("windows-1252"));

**Comment by sfblap** [comment]
thank you !

**Comment by albfernandez** [comment]
Now charset info is writed to file. UTF-8 is not supported, but you can write files which can be opened with other software
