### ISSUE TITLE
error when parsing leading space characters

### ISSUE THREAD

**Issue by Nicole-6246** [albfernandez/javadbf#92]
If the field contains space character at the begining, the "field.getLength()" counts the length contains length of non-space, then the "dataInputStream.read" only cut the first length, so return the spaces but cut off characters at the end.

below is where it happened:
	protected Object getFieldValue(DBFField field) throws IOException {
		int bytesReaded = 0;
		switch (field.getType()) {
		case CHARACTER:
			byte b_array[] = new byte[field.getLength()];
			bytesReaded = this.dataInputStream.read(b_array);

**Comment by albfernandez** [comment]
Hi
I've released a new version. It's the bug yet happening in the latest version?
if yes, can you provide some sample file / code to reproduce de bug?

Thanks
