### ISSUE TITLE
supportsFieldFlags is always false for F5 and FB

### ISSUE THREAD

**Issue by ztyzbb** [albfernandez/javadbf#94]
com.linuxense.javadbf.DBFHeader#supportsFieldFlags
```java
private boolean supportsFieldFlags() {
    return this.signature == 0x2 || this.signature == 0x30 || this.signature == 0x31 || this.signature == 0xF5 || this.signature == 0xFB;
}
```
Left operand is in {-128..1, 3..47, 50..127}

May cause problem when reading an F5 FB file, each field's `reserv2` will lost.

**Comment by albfernandez** [comment]
I'm not sure what do you mean. Can you provide a sample code or file?

**Comment by ztyzbb** [comment]
Sorry reply late, I'm too busy these days.
[Code here](https://github.com/albfernandez/javadbf/blob/932374e972d805b36a4d12162638c5be00cca88c/src/main/java/com/linuxense/javadbf/DBFHeader.java#L178)
In java, byte range is 127 to -128, so it's always false when signature compared to 0xF5 and 0xFB.
Test code, dbase_f5,dbf located in test resource, b1 is always false.
```java
public static void main(String[] args) throws IOException {
    DataInputStream dataInputStream = new DataInputStream(Test1.class.getResourceAsStream("/dbase_f5.dbf"));
    byte b = dataInputStream.readByte();
    boolean b1 = b == 0xF5;
}
```

**Comment by albfernandez** [comment]
Thanks for your detailed info.
I'm releasing a fixed version
